on: push
jobs:
    build-node:
      runs-on: ubuntu-latest
      container: node:16
      steps:
        - run: node --version
        - run: apt-transport-https 
        - run: apt-get install -y net-tools
        - run: ifconfig
        - uses: actions/checkout@v3
        - run: node server.js 8000
